### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by Aarontheissueguy** [comment]
Hi thank you for contributing to WaydroidHelper. In our latest version we changed a lot of stuff regarding translation. We now added proper support for it in our code and contributions can be made on [POEditor](https://poeditor.com/join/project?hash=DIES6h7HNF)

Thank you ;)

**Comment by Vistaus** [comment]
Nice! I just requested the Dutch language on POEditor and will contribute there then. :-)

**Comment by Aarontheissueguy** [comment]
Dutch should be an option now in POEddit

**Comment by Vistaus** [comment]
I can confirm that Dutch has been added to POEditor. Thank you. :-)

**Pull request closed without merging**
